stages:
  - update
  - test
  - build

update_base_image:
  stage: update
  image: docker:latest
  rules:
    - if: '$UPDATE_BASE_IMAGE == "true"'
  script:
    - docker login -u gitlab-ci-token -p "$CI_JOB_TOKEN" "$CI_REGISTRY"
    - docker build --file=".gitlab/docker/Dockerfile" --tag="$BASE_IMAGE" .
    - docker push "$BASE_IMAGE"

run_sh_integration_tests:
  stage: test
  image: "$BASE_IMAGE"
  dependencies: []
  needs: []
  rules:
    - when: always
      if: '$UPDATE_BASE_IMAGE != "true"'
  script:
    - pip install -e .[AWS,DEV]
    - pytest -m "sh_integration"

build_docker_image:
  stage: build
  needs: []
  rules:
    - if: $CI_COMMIT_TAG # run only on releases
      when: always
      variables:
        CUSTOM_RUN_TAG: auto # this will create images with the latest tag and the version tag
        LAYER_NAME: dotai-eo
    - when: manual
  trigger:
    project: eo/infra/docker
  allow_failure: true
