version: 2

sphinx:
  configuration: docs/source/conf.py

python:
  version: 3.8
  install:
  - method: pip
    path: .
    extra_requirements:
    - docs

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.10"
  jobs:
    pre_build:
      - cd docs
      - make autodoc
      - cd ..
