name: build

on:
  pull_request:
    types: closed
    branches:
      - "master"
      - "develop"

jobs:
  mirror-and-integration-test-on-gitlab:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Mirror + trigger CI
        uses: SvanBoxel/gitlab-mirror-and-ci-action@master
        with:
          args: "https://git.sinergise.com/eo/code/sentinelhub-py-dev/"
        env:
          FOLLOW_TAGS: "true"
          GITLAB_HOSTNAME: "git.sinergise.com"
          GITLAB_USERNAME: "github-action"
          GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
          GITLAB_PROJECT_ID: "354"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
