name: trigger

on:
  push:
    branches:
      - "add-docker-image-build-trigger-job"
  release:
    types:
      - published

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Install requirements
        run: apt install -y curl

      - name: Trigger API
        run: >
          curl -X POST --fail \
            -F token=${{ secrets.GITLAB_PIPELINE_TRIGGER_TOKEN }} \
            -F ref=main \
            -F variables[CUSTOM_RUN_TAG]=auto \
            -F variables[LAYER_NAME]=dotai-eo \
            https://git.sinergise.com/api/v4/projects/1031/trigger/pipeline
